### ISSUE TITLE
Is there a way to change the file names?

### ISSUE THREAD

**Issue by SynaDesigns** [andreblue/andre_sharex_uploader#1]
Is there a way to make the screenshots have like a random number type name like most other screenshot sites?

**Comment by andreblue** [comment]
Commit done 76202b2feadeb7eb604fd39389c28a2a6b9d06de should let you change that. May look at adding some other custom titles in a tad.

**Comment by SynaDesigns** [comment]
Thank you. :)

**Comment by andreblue** [comment]
np
